openapi: 3.0.1
info:
  title: Binary Sort Service API
  description: API to sort numbers based on binary representation.
  version: "1.0"
  servers:
    - url: http://localhost:8080
paths:
  /binary-sort:
    post:
      summary: Sorts a list of integers by the number of ones in their binary representation.
      tags:
        - Binary Numbers
      requestBody:
        description: List of integers to be sorted.
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
              minItems: 1
              maxItems: 50
              description: "Array of integers to be sorted. Maximum 50 integers, each must be a three-digit number."
            example: [7, 2, 1, 9, 5, 3, 8, 25, 42]
      responses:
        '200':
          description: Sorted list of integers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
              example: [1, 2, 8, 3, 5, 9, 7, 25, 42]
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                emptyList:
                  summary: Empty list
                  value:
                    error: "Input array must not be empty."
                invalidSize:
                  summary: Exceeds maximum size
                  value:
                    error: "Input must contain at most 50 integers."
                invalidType:
                  summary: Non-integer elements
                  value:
                    error: "Input array must contain only integers."
                invalidValue:
                  summary: Invalid values
                  value:
                    error: "Each integer must be a three-digit number."
